apiVersion: v1
kind: cluster config
metadata: 
  name: simple-webapp-flask
  region: ap-south-2

  managedNodeGroups:
    - name: my-node 
      instanceTypes: ["t3.medium"]
      desiredCapacity: 2
      volumeSize: 20
      ssh:
        allow: true